### PR TITLE
feat(alert_condition): add error_rate_percentage

### PR DESCRIPTION
**Pull request by sleistner**
BREAKING CHANGE: update to new relic provider 2.0

renamed variables:
since_value => evaluation_offset

### CODE REVIEW

**Comment by sleistner** [comment]
#### `terraform validate` Failed

```

Error: Missing required argument

  on main.tf line 7, in provider "newrelic":
   7: provider "newrelic" {

The argument "account_id" is required, but no definition was found.

```

*Workflow: `Terraform Lint`, Action: `hashicorpterraform-github-actions3`, Working Directory: `./tests`, Workspace: `default`*

**Comment by sleistner** [comment]
#### `terraform fmt` Failed

<details><summary><code>./tests/main.tf</code></summary>

```diff
 }
 
 provider "newrelic" {
-  version = "~> 2.0.0"
-  api_key = "12345"
+  version    = "~> 2.0.0"
+  api_key    = "12345"
   account_id = "12345"
 }
 
```

</details>

*Workflow: `Code checks and tests`, Action: `hashicorpterraform-github-actions1`, Working Directory: `.`, Workspace: `default`*

**Review by alexsavio — APPROVED** [review]
LGTM!

**Pull request merged**
